# Generated by Django 6.0.6 on 2026-06-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='prix_vente',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sous_total',
            field=models.IntegerField(editable=False),
        ),
    ]
