# Generated by Django 6.0.5 on 2026-06-03 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_stockmovement"),
        ("purchases", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="achat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mouvements",
                to="purchases.purchase",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="vente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mouvements",
                to="sales.sale",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
