# Generated by Django 6.0.6 on 2026-06-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_inventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prix_achat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='prix_vente',
            field=models.IntegerField(),
        ),
    ]
